E_CLASSROOM-253 [UI] Edit questions form
framgia/sph-classroom-els-fe pull request #107
Opened 2022-02-15 05:24 UTC by catampongan

### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-253
### Definition of Done
- [ ] 
- [ ] 

### Commands to Run

### Notes
#### Main note
- 
#### Pages Affected
- 

### Scenarios/ Test Cases
- [ ] it should `expected behavior` when `condition` 
#### User Interface
- [ ] when `action` should `expected behavior`
#### User Experience 
- [ ] when `action` should `expected behavior`
#### Functionality
- [ ] it should return value when `action`
### Screenshots

2022-02-16 09:01 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +            )}
maybe we can put this in a function and use switch case again. if ever we need to add more choices, it will be easier

2022-02-16 09:01 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +              </Dropdown.Menu>
put the choices in a variable then loop through it then display

2022-02-16 09:01 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +                  <Dropdown.Item eventKey="60">60 seconds</Dropdown.Item>
put the choices in a variable then loop through it then display

2022-02-16 09:01 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.module.scss
> +  background-color: #ffffff;
use global variable

2022-02-16 09:06 UTC, karlolee50 requested changes
Review time: 15 minutes
Comment/s: 4

2022-02-16 09:17 UTC, ErickDoroy commented
### PR #107

- [x] Correct choices are present in the dropdown fields
- [x] Cancel and Save buttons are present
- [x] Design is the same with figma. 

-------------
-------------

### Comment/s
- [ ]  Dropdown must hide.
- [ ] Text inside the dropdown should have the same style in figma

![adminquestion](https://user-images.githubusercontent.com/89514595/154232732-9b77f47e-46a2-4866-9eca-5012c51f2009.PNG)
- [ ] Focus color should same as figma.

![adminquestion1](https://user-images.githubusercontent.com/89514595/154233028-5e34c626-5dbc-40f1-8d6f-3e5e683d94d5.PNG)

-----------
Total testing hr. 0.75 hr.

2022-02-17 03:31 UTC, Teraaay commented
### Approved PR #104
- [x] Text fields and dropdown fields are present
- [x] Correct choices are present in the dropdown fields
- [x] Cancel and Save buttons are present
- [x] Design is the same as the Figma
- [x] Able to switch from the Identification and Multiple Choice questionnaire form.

Able to fix the comments
- [x] Text inside the dropdown has the same style as the one in Figma
- [x] Hover text is the as the one in Figma
- [x] Answer input should not be resizable

### Screenshot/s
> ![QUIZ EDIT](https://user-images.githubusercontent.com/91049234/154399826-a3333589-6781-475c-801b-b43bff950d2f.gif)


----
- Total Test time: 0.5 hr
- Total Iterations: 1
- Total Comments: 2

2022-02-17 05:03 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +          </div>
please create another component file and put the contents there to avoid bloating this file

2022-02-17 08:50 UTC, karlolee50 approved these changes

2022-02-17 08:51 UTC, merged