[Wip] E_CLASSROOM-255 [FE/BE] Implement adding a new quiz
framgia/sph-classroom-els-fe pull request #109
Opened 2022-02-15 11:49 UTC by ErickDoroy

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-255
### Definition of Done
- [x] Modal will popup when user clicks on "Add Quiz" button
- [x] User can input text and select category where the quiz will belong
- [x] User can add a new quiz

### Commands to Run

### Related PR:
- https://github.com/framgia/sph-classroom-els-be/pull/50
### Notes
#### Main note
- 
#### Pages Affected
- 

### Scenarios/ Test Cases
- [ ] Modal will popup when user clicks on "Add Quiz" button
- [ ] User can input text and select category where the quiz will belong
- [ ] User can add a new quiz
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
![addquizmodal](https://user-images.githubusercontent.com/89514595/154056476-e451d12c-5d7f-4c44-aaaf-b1d50c53b3a5.PNG)

2022-02-16 05:22 UTC, CaneteJoash commented
### Working 

- [x] Able to add quiz in the admin side.
- [x] Modal will popup when user clicks on "Add Quiz" button.
- [x] Modal will Close after the user add a new quiz.
- [x] Able to add the new quiz in the database. 

![SUCCESS](https://user-images.githubusercontent.com/89382909/154200292-1dab810c-9343-4b45-958e-1a6fe80244f1.gif)

-------------
-------------

### Comment/s

- [ ] Please fix the 'Add a Quiz' font weight. refer this in figma.

### figma
![image](https://user-images.githubusercontent.com/89382909/154200359-e862df91-bf78-4c0c-acbd-0552cdc41542.png)

### APP
![image](https://user-images.githubusercontent.com/89382909/154200167-70f4d49d-29f3-4915-97bb-17eee1847d6d.png)

- [ ] When we click the 'Go Back' button, the user must redirect to 'quizzes' not to the 'categories'.

![error should not redirect to categories](https://user-images.githubusercontent.com/89382909/154200695-838286db-4b16-4e8a-b356-71cab5f3ef33.gif)

- [ ] After clicking the 'Add Quiz' button the new quiz must automatically display in the list of quizzes.

![error should display the new quiz in the table](https://user-images.githubusercontent.com/89382909/154200835-a04657b1-696a-40b5-b471-fa670afe1df9.gif)

- [ ] Please fix the components, When we try to minimized the text input in the 'Instruction', the button bellow will push downwards. Refer my record. 

![error please fix the components](https://user-images.githubusercontent.com/89382909/154201044-3d0b36dc-d6c8-4b41-b3fd-d440b711104e.gif)

-----------
Total testing hr. 1.5 hr.

2022-02-16 09:06 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.js
> +    console.log(data);
remove if not used.

i think the data variable is not used as well?

2022-02-16 09:06 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.js
> +              Go Back
fix indentation

2022-02-16 09:06 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.js
> +              Cancel
fix indentation

2022-02-16 09:06 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.js
> +              Add Quiz
fix indentation

2022-02-16 09:06 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.module.scss
> +  background-color: #c0d5d8;
use global variable

2022-02-16 09:07 UTC, karlolee50 commented on src/api/Quiz/index.js
> +      url: '/admin_add',
update the URL endpoint due to my comment of my BE comment

2022-02-16 09:08 UTC, karlolee50 requested changes
Review time: 15 minutes
Comment/s: 6

2022-02-16 09:22 UTC, CaneteJoash commented
### Working 

- [x] 'Add a Quiz' font weight fixed
- [x] Able to add quiz and the new quiz must automatically display in the list of quizzes.
- [x] Instruction input disable resize input was fixed.
 
![success](https://user-images.githubusercontent.com/89382909/154233804-3f8183a6-85d1-4c97-a5a4-5a6d57a03a18.gif)

### Comment/s

- [ ] Please fix the 'Go back Button' when I click it, my changes will be save.
![Error back button](https://user-images.githubusercontent.com/89382909/154233964-448ff51e-c01a-4976-a965-b3ab01a604ed.gif)

--------

Total Testing hr. : .25 hr

2022-02-16 10:01 UTC, CaneteJoash commented
### Comment 

- [x] please remove the underline above the modal. refer to my record.
![remove the line](https://user-images.githubusercontent.com/89382909/154240952-f5750937-b3dc-44a4-815b-d3f611607aa9.gif)

2022-02-16 12:09 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.js
> +        </Modal>
can we move this into a different component to avoid bloating the QuizList component

2022-02-18 05:08 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/components/index.js
> +export default ModalRender;
add extra line

2022-02-18 05:09 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/components/index.js
> +import React, { useEffect } from 'react';
put this component in another folder. not just in the /components folder.

for example /components/QuizModal/index.js

2022-02-18 05:13 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizList/index.js
> +import ModalRender from './components';
change ModalRender name to something like QuizModal or AddQuizModal

2022-02-18 06:22 UTC, catampongan commented
## Approved PR #109 
- [x] Able to add quiz in the admin side.
- [x] Modal will popup when user clicks on "Add Quiz" button.
- [x] Modal will Close after the user add a new quiz.

----------------
![image](https://user-images.githubusercontent.com/89382692/154627900-703e3fca-3faa-492a-a3ce-76414956e870.png)
![Screenshot 2022-02-18 135351](https://user-images.githubusercontent.com/89382692/154627933-9468156b-dbb9-4e8b-8be8-056225fd9ae2.png)

-----------
- Total Test Time: 2 hrs
- Total Iterations: 3
- Total Comments: 6

2022-02-18 06:49 UTC, karlolee50 approved these changes

2022-02-18 06:49 UTC, merged