E_CLASSROOM-298 [FE/BE] [Admin] Profile Account Page
framgia/sph-classroom-els-fe pull request #134
Opened 2022-03-08 09:36 UTC by ErickDoroy

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-298
### Definition of Done
- [x] Layout is the same with the figma design
- [x] Fields are dynamic
- [x] Clicking on "Edit Profile" button will redirect to "Edit Account Info" page
- [x] Clicking on "Change Password" button redirect to "Change Password" page
- [x] User can upload and change profile picture

### Commands to Run

## Related PR:
- 
### Notes
#### Main note
- http://localhost:3003/admin/profile
#### Pages Affected
- Profile 
  > http://localhost:3003/admin/profile
- Profile Edit
  > http://localhost:3003/admin/profile/edit
- Edit Password
  > http://localhost:3003/admin/profile/edit-password

### Scenarios/ Test Cases
- [x] Layout is the same with the figma design
- [x] Clicking on "Edit Profile" button will redirect to "Edit Account Info" page
- [x] Clicking on "Change Password" button redirect to "Change Password" page
- [x] User can upload and change profile picture
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
![adminprofile2](https://user-images.githubusercontent.com/89514595/157209381-2be3f2f7-4318-4f0a-a3b9-9253fbbd667d.gif)

2022-03-08 10:18 UTC, catampongan commented
## Working
- [x] User can edit profile picture

## Comment
- [ ] Buttons are not clickable both `Change password` and `Edit`
- [ ] Button in modal should be the same on default button
- [ ] Align modal on profile edit
-----------------------
![Screenshot 2022-03-08 180836](https://user-images.githubusercontent.com/89382692/157216167-4556ce6c-bb6d-4eae-8ced-9766bdd3e2ea.png)
![bugfix-1](https://user-images.githubusercontent.com/89382692/157216317-def4f1f7-482a-47a6-aa3c-04cce029a0ca.gif)
-------------------------
- Total Test Time: 0.25 hr

2022-03-08 11:02 UTC, catampongan commented
## Approved PR #134 
- [x]  User can edit profile picture
- [x] Able to redirect change password page when `Change password` button is clicked
- [x] Able to redirect edit info page when `Edit` button is clicked
- [x] Design is the same in Figma
- [x] Layout is dynamic
-------------------
![image](https://user-images.githubusercontent.com/89382692/157225483-d6b5f954-c4d1-4773-98c8-dbce7df411cc.png)
![task-298](https://user-images.githubusercontent.com/89382692/157225649-094795ef-1d8f-4d42-9dbc-0d30716de191.gif)
---------------
- Total Test Time: 0.5 hr
- Total Iterations: 1
- Total Comments: 3

2022-03-09 03:12 UTC, karlolee50 commented on src/pages/admin/profile/ProfileView/index.js
> +    }
use .then and .catch

2022-03-09 03:12 UTC, karlolee50 commented on src/pages/admin/profile/ProfileView/index.js
> +                Change Password
fix indentation

2022-03-09 03:12 UTC, karlolee50 commented on src/pages/admin/profile/ProfileView/index.js
> +                Email
fix indentation

2022-03-09 03:13 UTC, karlolee50 commented on src/pages/admin/profile/ProfileView/index.js
> +                Edit
fix indentation

2022-03-09 03:13 UTC, karlolee50 commented on src/pages/admin/profile/ProfileView/index.js
> +                Name
fix indentation

2022-03-09 03:14 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 2

2022-03-09 03:55 UTC, karlolee50 approved these changes

2022-03-09 03:55 UTC, merged