E_CLASSROOM-337 [FE/BE] Fix change category in add/edit question
framgia/sph-classroom-els-fe pull request #152
Opened 2022-03-16 07:44 UTC by CaneteJoash

### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-337

### Definition of Done
- [x] User can change category of the quiz
- [x] Add/edit question functionality is not broken

### Commands to Run
N/A

### Related PR
BE: 
### Notes 
#### Main note
N/A
#### Pages Affected
- http://localhost:3003/admin/quizzes/1
- http://localhost:3003/admin/quizzes/1/edit

### Scenarios/ Test Cases
- [x] User can change category of the quiz
- [x] Add/edit question functionality is not broken
#### User Interface
- [ ] when click the save button the location in quizDetail should update
#### User Experience 
N/A
#### Functionality
- [ ] it should return to Quiz Detail and update the location.
### Screenshots
![image](https://user-images.githubusercontent.com/89382909/158539864-6d8202ba-6342-4257-8fd6-bba670152697.png)
![image](https://user-images.githubusercontent.com/89382909/158540012-84728a4d-0d53-4c8d-bb49-44f75cd49962.png)
![image](https://user-images.githubusercontent.com/89382909/158540214-de21430e-8e05-49ea-8fb0-43cd212a7b12.png)
![image](https://user-images.githubusercontent.com/89382909/158540279-0be6e7fb-590a-4641-9c54-880624fbfc38.png)
![image](https://user-images.githubusercontent.com/89382909/158540467-48d9663e-f2bd-4279-abdd-7f380a7fd88c.png)

2022-03-16 09:42 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizDetail/index.js
> +      });
include a .catch statement

2022-03-16 09:42 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizDetail/index.js
> +      idx === 0
```suggestion
      !idx
```

2022-03-16 09:43 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizDetail/index.module.scss
> +}
add extra line

2022-03-16 09:44 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +  const [saveLocation, setSaveLocation] = useState(false);
please group together the variables. for example group together the ones using useState, not using useState, etc..

2022-03-16 09:44 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +        });
add a .catch

2022-03-16 09:44 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +      idx === 0
```suggestion
      !idx
```

2022-03-16 09:46 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 6

2022-03-16 10:20 UTC, catampongan commented
## Approved PR #152 
- [x] Able to change the category of the quiz
- [x] Add/edit button is functional
- [x] Redirected to quizzes after saving the changes
------------------------------
![task-337](https://user-images.githubusercontent.com/89382692/158567261-d953c975-499d-484f-9cf3-8f350d681189.gif)
![task-337](https://user-images.githubusercontent.com/89382692/158567371-b443415a-77ff-405a-8b5f-d64584d58fd1.png)
![Task-337-1](https://user-images.githubusercontent.com/89382692/158568221-b67ff7e5-8a52-4ccd-9357-d72180a956d2.png)

--------------------------------
- Total Test Time: 0.5 hr
- Total Iterations: 0
- Total Comments: 0

2022-03-18 01:59 UTC, catampongan commented
## Approved PR #152 
- [x] Able to change the category of the quiz
- [x] Add/edit button is functional
- [x] Redirected to quizzes after saving the changes
---------------------------------
![task-337](https://user-images.githubusercontent.com/89382692/158922772-0af57beb-da1e-49fe-a0f4-5ab28300caa9.png)
![Task-337-1](https://user-images.githubusercontent.com/89382692/158922778-10e3be4b-979d-4d66-9c25-24cec69bd5cb.png)
![task-337](https://user-images.githubusercontent.com/89382692/158922956-d1de260f-3ccc-474c-93ce-70bf8da0aa96.gif)

-----------------------
- Total Test Time: 0.75 hr
- Total Iterations: 1
- Total Comments: 1

2022-03-18 02:17 UTC, karlolee50 approved these changes

2022-03-18 02:18 UTC, merged