E_CLASSROOM-324 [FE/BE] Display related subcategories and quizzes for the selected category
framgia/sph-classroom-els-fe pull request #153
Opened 2022-03-16 09:11 UTC by ErickDoroy

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-324
### Definition of Done
- [x] When selecting a category page, create another section for quizzes below the subcategories
- [x] Display all quizzes related to that category
- If there's no related quizzes or subcategories, then put message "No related subcategories to show." or "No related quizzes to show." (or something alike)
- [x] Make API change if needed

### Commands to Run

## Related PR:
- https://github.com/framgia/sph-classroom-els-be/pull/77
### Notes
#### Main note
- http://localhost:3003/categories/1/sub?page=1&page=1
#### Pages Affected
- Student subcategory page

### Scenarios/ Test Cases
- [ ] it should view the subcategory and quizzes related to that selected category
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
![studentcatquiz](https://user-images.githubusercontent.com/89514595/158555746-5066a44e-2db9-487b-af45-e4433e77fb13.gif)

2022-03-16 10:38 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
> +            style={{ fontWeight: 'bold', fontSize: '18px', color: '#48535B' }}
use class name here instead

2022-03-16 10:39 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
> +            style={{ fontSize: '12px', color: '#48535B', marginTop: '5px' }}
use class name here also

2022-03-16 10:39 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
> +              }}
here as well

2022-03-16 10:39 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
> +  } */
remove if not used

2022-03-16 10:39 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
> +  } */
remove if not used

2022-03-16 10:40 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
> +  {</Card.Text>} */
remove if not used

2022-03-16 10:40 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +
remove if not used

2022-03-16 10:41 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +      {data === null ? (
```suggestion
      {!data ? (
```

2022-03-16 10:42 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +            </div>
the no results message is repeating. can we put it in a function instead?

2022-03-16 10:42 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +            </div>
refer to my previous comment

2022-03-16 10:43 UTC, karlolee50 requested changes
Review time: 15 minutes
Comment/s: 4

2022-03-16 10:54 UTC, catampongan commented
## Working
- [x] Selecting a category page has divided into 2 section the sub categories and quizzes section

## Comment
- [ ] Remove space if there is no content on that area

-------------------------------------
![image](https://user-images.githubusercontent.com/89382692/158574335-08961828-2e43-4053-a76a-78cc73b9fd1b.png)
![task-324](https://user-images.githubusercontent.com/89382692/158574374-4027fb08-c9b0-4ae0-9644-b53aa732ec8c.gif)

-----------------------------------
- Total Test Time: 0.25 hr

2022-03-17 03:15 UTC, catampongan commented
# Approved PR #153 
- [x] Selecting a category page has divided into 2 section the sub categories and quizzes section
- [x] Displays all quizzes related to that category
-----------------------
![image](https://user-images.githubusercontent.com/89382692/158729492-3816ee84-eb84-4948-8de4-b83da43a6c90.png)

----------------------
- Total Test Time: 0.5 hr
- Total Iterations: 1
- Total Comments: 1

2022-03-17 03:50 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +
```suggestion
  const noResultMessage = (messageText) => {
    return (
      <div className={style.noResultsMessage}>
        <p className={style.message}>{messageText}</p>
      </div>
    );
  }

```

use ES6 function convention and update the function name as well as the argument being passed

2022-03-17 03:50 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +            <div>{message('NO RESULTS FOUND')}</div>
```suggestion
            <div>{noResultMessage ('NO RESULTS FOUND')}</div>
```

update the function name here as well after updating the previous one

2022-03-17 03:50 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/index.js
> +            <div>{message('NO RELATED QUIZZES FOUND')}</div>
update here as well

2022-03-17 03:51 UTC, karlolee50 requested changes
Review time: 5 minutes
Comment/s: 1

2022-03-18 02:19 UTC, karlolee50 approved these changes

2022-03-18 02:36 UTC, merged