[WIP] E_CLASSROOM-326 [FE/BE] Move To function in Category Hierarchy Page
framgia/sph-classroom-els-fe pull request #160
Opened 2022-03-18 12:22 UTC by ErickDoroy

### Issue Link

### Definition of Done
- [ ] 
- [ ] 

### Commands to Run

### Notes
#### Main note
- 
#### Pages Affected
- 

### Scenarios/ Test Cases
- [ ] it should `expected behavior` when `condition` 
#### User Interface
- [ ] when `action` should `expected behavior`
#### User Experience 
- [ ] when `action` should `expected behavior`
#### Functionality
- [ ] it should return value when `action`
### Screenshots

2022-03-21 06:15 UTC, karlolee50 commented on src/pages/admin/categories/CategoryHierarchy/index.js
> +export default CategoryHierarchy;
add extra link

2022-03-21 07:57 UTC, CaneteJoash commented
## Working
- [x] Upon clicking the "Move To", Able todisplay a modal for changing location.
- [x]  Behavior is the same with the "Change Location" in other pages
- [x] After saving, should stay in the same page but reflect the new list
- [x] Able to move the category to other Category.
- [x] Able to add a child and display it in the category where it belong.

### Success Screen Shots
![success](https://user-images.githubusercontent.com/89382909/159219916-f81baedb-75e9-4997-82ae-d636a1866767.gif)
![success 1](https://user-images.githubusercontent.com/89382909/159220922-cdb6f082-c7a7-4c0a-8f19-2db43df96ca4.gif)
![success 2](https://user-images.githubusercontent.com/89382909/159220921-13705745-779c-4f6c-8bdc-a976542e9d02.gif)

## Comment
- [ ] After moving the Category to root, and if there is no sub Category for a category please put A message telling the user that there is no Category or something else. 

![Comment](https://user-images.githubusercontent.com/89382909/159220284-20f31aa6-06bb-480f-9364-732912859f25.gif)


- [ ] After adding a child category, If I change the location to other category, after saving it, please redirect the child category to its parent category. refer my screenShots.


![test for error](https://user-images.githubusercontent.com/89382909/159221673-10bbfab0-0093-4a29-aa33-98018dc8e381.gif)


------------------------------

- Total Test Time: 1 hr
- Comment: 2

2022-03-21 10:34 UTC, karlolee50 commented on src/components/ChangeLocation/index.js
> +          )}
did you check the other pages using the ChangeLocation component as well? are they not affected with this change?

2022-03-21 10:35 UTC, karlolee50 commented on src/pages/admin/categories/AddEditCategory/index.js
> +            modalHeaderTitle={modalHeaderTitle}
just pass as a normal string

2022-03-21 10:36 UTC, karlolee50 commented on src/components/ChangeLocation/index.js
> +  modalHeaderTitle,
you can have a default value here so that the existing pages using "Change Location" will not be affected

2022-03-21 10:36 UTC, karlolee50 commented on src/pages/admin/categories/CategoryHierarchy/index.js
> +  ];
change to string

2022-03-21 10:38 UTC, karlolee50 commented on src/pages/admin/categories/AddEditCategory/index.js
> +
change to string

2022-03-21 10:38 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 6

2022-03-21 10:38 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +
change to string

2022-03-21 12:01 UTC, karlolee50 commented on src/pages/admin/categories/CategoryHierarchy/index.js
> +          console.log(categories);
remove if not used

2022-03-21 12:02 UTC, karlolee50 commented on src/pages/admin/quizzes/QuizEdit/index.js
> +
change to string instead of object

2022-03-21 12:02 UTC, karlolee50 commented on src/pages/admin/categories/CategoryHierarchy/index.js
> +export default CategoryHierarchy;
add extra line

2022-03-21 23:20 UTC, CaneteJoash commented
### APPROVED PR #160  

- [x] Upon clicking the "Move To", Able todisplay a modal for changing location.
- [x]  Behavior is the same with the "Change Location" in other pages
- [x] After saving, should stay in the same page but reflect the new list
- [x] Able to move the category to other Category.
- [x] Able to add a child and display it in the category where it belong.
- [x] able to display 'no subcategory message' if there is no sub category in the parent category.

### Success Screen Shots
![success](https://user-images.githubusercontent.com/89382909/159219916-f81baedb-75e9-4997-82ae-d636a1866767.gif)
![success 1](https://user-images.githubusercontent.com/89382909/159220922-cdb6f082-c7a7-4c0a-8f19-2db43df96ca4.gif)
![success 2](https://user-images.githubusercontent.com/89382909/159220921-13705745-779c-4f6c-8bdc-a976542e9d02.gif)
![success 3](https://user-images.githubusercontent.com/89382909/159378282-5480e514-c150-47be-ac98-c3d7d833cb94.gif)

------------------------------

- Total Test Time: 1 hr
- Total Comment: 1
- Total Iteration: 1

2022-03-22 02:21 UTC, karlolee50 approved these changes

2022-03-22 02:21 UTC, merged