E_CLASSROOM-321 [UI] Fix content width and inconsistencies of all pages
framgia/sph-classroom-els-fe pull request #162
Opened 2022-03-21 07:07 UTC by CaneteJoash

### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-321

### Definition of Done
- [X] Wrap main content with .container class
- Target pages : Dashboard, Categories, Learnings, Profile
- [X] Fix consistency of the page title font-size to 32px
- [X] Fix column inconsistency with Profile page
- [X] Fix the scroll to each page
- Make the whole page scrollable, not the "white area"

### Commands to Run
N/A

### Notes
- No need to wrap Students page with container class, since it is not full width
#### Main note
- 
#### Pages Affected
- http://localhost:3003/
- http://localhost:3003/categories
- http://localhost:3003/students
- http://localhost:3003/students/3
- http://localhost:3003/learnings
- http://localhost:3003/profile
- http://localhost:3003/categories/4/sub

### Scenarios/ Test Cases
- [ ] Wrap main content with .container class
- Target pages : Dashboard, Categories, Learnings, Profile
- [ ] Fix consistency of the page title font-size to 32px
- [ ] Fix column inconsistency with Profile page
- [ ] Fix the scroll to each page
- Make the whole page scrollable, not the "white area"
#### User Interface
N/A
#### User Experience 
N/A
#### Functionality
N/A
### Screenshots
![image](https://user-images.githubusercontent.com/89382909/159217171-cd9f8df6-2131-4a96-bd29-b49b7369ca4e.png)
![image](https://user-images.githubusercontent.com/89382909/159217193-fe32bf79-6d49-4b5f-888a-82bc3d28bb77.png)
![image](https://user-images.githubusercontent.com/89382909/159217227-2c03c816-a1a5-4df7-81de-4d0e5e3d481b.png)
![image](https://user-images.githubusercontent.com/89382909/159217273-b193e283-4a69-4045-90ea-91c964dc74cd.png)
![image](https://user-images.githubusercontent.com/89382909/159217283-3e30bcb8-fc78-4515-b6c6-297c023f35dd.png)
![image](https://user-images.githubusercontent.com/89382909/159217320-5475505a-11ef-4378-b09b-8e2201e07791.png)
![image](https://user-images.githubusercontent.com/89382909/159217330-832e0980-6d2e-4e14-a7b5-4a73e78d3b2e.png)
![image](https://user-images.githubusercontent.com/89382909/159217354-b8e7d878-6e4e-4252-98ea-0da693e42d4b.png)
![image](https://user-images.githubusercontent.com/89382909/159217410-b851ec0d-cf27-4545-8c3b-f7c25f990d7d.png)
![image](https://user-images.githubusercontent.com/89382909/159217438-d1d48a5d-f8de-45a9-98be-6991db7f5745.png)
![image](https://user-images.githubusercontent.com/89382909/159217485-593a4723-453f-4a02-94df-cd2b7e8ba74d.png)
![image](https://user-images.githubusercontent.com/89382909/159217538-545d8a9d-5a6a-4efc-b004-adf3379b112c.png)

2022-03-21 08:38 UTC, ErickDoroy commented
## Working
- [X] Wrap main content with .container class
- Target pages : Dashboard, Categories, Learnings, Profile
- [X] Fix consistency of the page title font-size to 32px
- [X] Fix column inconsistency with Profile page
- [X] Fix the scroll to each page
- Make the whole page scrollable, not the "white area"
## Comment
- [ ] Please don't change anything on the student page
![image](https://user-images.githubusercontent.com/89514595/159227010-db89c113-0952-4b73-b79f-01b785c58b7d.png)
- [ ] Change the quiz taken area in the Dashboard page to it's original placement
![image (3)](https://user-images.githubusercontent.com/89514595/159227428-3cd35bff-be17-4738-a69d-3bfd2692d661.png)
to this
![image (4)](https://user-images.githubusercontent.com/89514595/159227461-07c97442-0b66-47f0-b83e-004b0af58fe7.png)
- [ ] In Category page balance the spacing 
![stucategory](https://user-images.githubusercontent.com/89514595/159227640-fc279ad6-144d-4886-868c-20f922d85c3e.PNG)
-------------------
- Total Test Time: 0.75 hr
- Total Iterations: 0
- Total Comments: 3

2022-03-21 11:46 UTC, ErickDoroy commented
## APPROVE #162 
- [x] Able to implement .container class
- [x] Fix the scroll to each page
- [x] Fix column inconsistency with Profile page
- [x] Fix consistency of the page title font-size to 32px
-----------
- Total Test Time: 0.75 hr
- Total Iterations: 0
- Total Comments: 0

2022-03-22 02:35 UTC, karlolee50 commented on src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
>  #cardHeader {
please convert to scss file and use global variables

2022-03-22 02:35 UTC, karlolee50 commented on src/pages/student/main/Dashboard/components/FriendsActivities/index.js
> +          {friendsActivities?.length > 0 ? (
```suggestion
          {friendsActivities?.length ? (
```

2022-03-22 02:36 UTC, karlolee50 commented on src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
>      align-items: center;
please convert to scss file and use global variables

2022-03-22 02:36 UTC, karlolee50 commented on src/pages/student/main/Dashboard/components/Recent/index.module.css
>      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
please convert to scss file and use global variables if applicable

2022-03-22 02:36 UTC, karlolee50 commented on src/pages/student/main/Dashboard/index.js
> +            {categorieslearned?.length > 0 ? (
```suggestion
            {categorieslearned?.length ? (
```

2022-03-22 02:38 UTC, karlolee50 commented on src/pages/student/profile/ChangePassword/index.js
> +                placeholder="match with new password"
```suggestion
                placeholder="Match with new password"
```

2022-03-22 02:43 UTC, karlolee50 commented on src/pages/student/quizzes/QuizList/index.module.css
>  .title {
please convert to scss file and use global variables if applicable

2022-03-22 02:43 UTC, karlolee50 commented on src/pages/student/students/StudentDetail/index.module.css
>  .student {
please convert to scss file

2022-03-22 02:44 UTC, karlolee50 commented on src/pages/student/students/StudentList/index.js
> +                  if (e.target.value.length === 0) {
```suggestion
                  if (!e.target.value.length) {
```

2022-03-22 02:45 UTC, karlolee50 commented on src/pages/student/students/StudentList/index.js
> +                    setPage(1);
can you put this in a function instead since it is being repeated in the other dropdown items. pass the necessary arguments

2022-03-22 02:46 UTC, karlolee50 commented on src/pages/student/students/StudentList/index.js
> +            {students === null ? (
```suggestion
            {!students ? (
```

2022-03-22 02:46 UTC, karlolee50 commented on src/pages/student/students/StudentList/index.module.css
> -.studentListHeader {
convert to scss

2022-03-22 02:47 UTC, karlolee50 requested changes
Review time: 20 minutes
Comment/s: 12

2022-03-23 02:37 UTC, karlolee50 approved these changes

2022-03-23 02:38 UTC, merged