[WIP] E_CLASSROOM-329 [FE/BE] Category Delete Function
framgia/sph-classroom-els-fe pull request #163
Opened 2022-03-21 08:02 UTC by ErickDoroy

### Issue Link

### Definition of Done
- [ ] 
- [ ] 

### Commands to Run

### Notes
#### Main note
- 
#### Pages Affected
- 

### Scenarios/ Test Cases
- [ ] it should `expected behavior` when `condition` 
#### User Interface
- [ ] when `action` should `expected behavior`
#### User Experience 
- [ ] when `action` should `expected behavior`
#### Functionality
- [ ] it should return value when `action`
### Screenshots

2022-03-22 05:39 UTC, catampongan commented
## Working
- [x] Displays confirmation modal when deleting a category
- [x] Able to delete a category/subcategory

## Comment
- [ ] Can delete a category that has subcategory after deleting a category
 * Delete a category that has no category
 * Delete a category that has a category (Without refreshing the page}
- [ ] Erase `cancel` button in the modal that can't delete a category
----------------------------------
![task-329](https://user-images.githubusercontent.com/89382692/159414903-4d9537ae-bbf1-455d-a830-49354c0ceba8.gif)
![task-329-2](https://user-images.githubusercontent.com/89382692/159414910-e6c1f4dd-e9e6-4b11-937c-03eb412689a4.gif)
![task-329](https://user-images.githubusercontent.com/89382692/159415154-2aa26764-84cd-4bfd-9a97-b1766539fe64.png)

-------------------------
- Total Test Time: 0.5 hr

2022-03-22 07:14 UTC, catampongan commented
## Approved PR #163 
- [x] Displays confirmation modal when deleting a category
- [x] Able to delete a category/subcategory
- [x] Couldn't delete category that has subcategories
----------------------------------------------------
![task-329](https://user-images.githubusercontent.com/89382692/159427233-15fad00e-64bc-479d-8d7b-e0fda0e6a544.png)
![task-329](https://user-images.githubusercontent.com/89382692/159427232-355a5efc-aaa5-420c-9692-8d516b127289.gif)
![task-329-2](https://user-images.githubusercontent.com/89382692/159427276-33a0f1f6-8076-4ecc-8b7c-3438a36c9c8d.gif)

----------------------------
- Total Test Time: 0.75 hr
- Total Iterations: 1
- Total Comments: 2

2022-03-23 02:43 UTC, karlolee50 commented on src/components/ConfirmationModal/index.js
> +export default ConfirmationModal;
add extra line

2022-03-23 02:46 UTC, karlolee50 commented on src/pages/admin/categories/CategoryHierarchy/index.js
> +                      }}
move to a function

2022-03-23 02:46 UTC, karlolee50 commented on src/pages/admin/categories/CategoryList/index.js
> +                }}
move to a function. it looks similar to my previous comment. maybe you can use the same function?

2022-03-23 02:46 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 3

2022-03-23 03:05 UTC, karlolee50 approved these changes

2022-03-23 03:05 UTC, merged