E_CLASSROOM-339 [Admin] [FE] Apply reusable components to Category forms
framgia/sph-classroom-els-fe pull request #164
Opened 2022-03-21 08:50 UTC by CaneteJoash

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-339
### Definition of Done
Apply reusable components to all category forms
* Add Category Forms
* Edit Category Forms
* Category hierarchy forms

- [x] Reusable components are applied in all pages above
- [x] Layout is not broken
- [x] Everything is still functioning correctly

### Commands to Run
N/A
### Notes
#### Main note
N/A
#### Pages Affected
- http://localhost:3003/admin/edit-category/6?categoryViewType=Hierarchy
- http://localhost:3003/admin/edit-category/1
- http://localhost:3003/admin/add-category

### Scenarios/ Test Cases
- [ ] Reusable components are applied in all pages above
- [ ] Layout is not broken
- [ ] Everything is still functioning correctly
#### User Interface
N/A
#### User Experience 
N/A
#### Functionality
N/A
### Screenshots
![image](https://user-images.githubusercontent.com/89382909/159229271-f6521a63-623f-4ca3-9c0b-40977e8e6924.png)
![image](https://user-images.githubusercontent.com/89382909/159229296-e4fa6351-b098-4cda-b27e-b9d201f06146.png)
![image](https://user-images.githubusercontent.com/89382909/159229316-cbe0ae9c-7ee8-4dec-b717-0ac578f5c7bb.png)

2022-03-22 09:46 UTC, catampongan commented
## Approved PR #164 
- [x] Layout is not broken
- [x] Everything is still functioning
------------------------------
![task-339](https://user-images.githubusercontent.com/89382692/159452647-efd55642-c240-4c9f-9cce-17ff8ff8e3c5.png)
![task-339-1](https://user-images.githubusercontent.com/89382692/159452653-2f0c8587-201f-4df9-88cc-9fd03aeef9fd.png)
![task-339-2](https://user-images.githubusercontent.com/89382692/159452657-ea3c29d4-efcd-4d4a-981d-56b27da34303.png)

---------------------
- Total Test Time: 0.25 hr
- Total Iterations: 0
- Total Comments: 0

2022-03-23 02:03 UTC, karlolee50 commented on src/pages/admin/categories/AddEditCategory/index.js
>                      : 'Save Category'}
you can put this in a function and return the string value of 'Add Category' or 'Save Category' instead of doing it inline

2022-03-23 02:03 UTC, karlolee50 commented on src/components/Button/index.js
> +    > buttonLabel : Pass a string value or a function for the button label .
do we really need to pass a function for the label? can we not just pass a string?

2022-03-23 02:05 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 2

2022-03-23 03:20 UTC, karlolee50 approved these changes

2022-03-23 03:20 UTC, merged