E_CLASSROOM-335 [FE/BE] Apply reusable components to /quizzes
framgia/sph-classroom-els-fe pull request #166
Opened 2022-03-22 07:40 UTC by Teraaay

### Issue Link

- https://framgiaph.backlog.com/view/E_CLASSROOM-335

### Definition of Done
* [x] Reusable components are applied in the route
* [x] Layout is not broken
* [x] Everything is still functioning correctly

### Notes
#### Pages Affected
- 

### Scenarios/ Test Cases
* [x] Reusable components are applied in the route
* [x] Layout is not broken
* [x] Everything is still functioning correctly

### Screenshots

2022-03-22 09:16 UTC, catampongan commented
## Approved PR #166 
- [x] Layout is not broken
- [x] Everything is still functioning
-----------------------------
![task-335](https://user-images.githubusercontent.com/89382692/159447049-2207b5b1-3652-4ee8-b8c3-9202e182a1b4.png)
![task-335-2](https://user-images.githubusercontent.com/89382692/159447055-fe1d5abd-6c33-4beb-afd4-70025c1cf248.png)
![task-335-3](https://user-images.githubusercontent.com/89382692/159447060-c1bac4f9-4cfb-4207-8c11-09da6296f3f3.png)
![task-335-5](https://user-images.githubusercontent.com/89382692/159447064-338c5999-d41d-4282-bb45-7d18230e6cd4.png)
![task-335-6](https://user-images.githubusercontent.com/89382692/159447067-49277116-3e4c-412f-a060-3039045f4fc7.png)

--------------------------
- Total Test Time: 0.25 hr
- Total Iterations: 0
- Total Comments: 0

2022-03-23 02:14 UTC, karlolee50 commented on src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
> +        <p>{`${question.question}`}</p>
i think no need for string interpolation since we are displaying only the variable
```suggestion
        <p>{question.question}</p>
```

2022-03-23 02:14 UTC, karlolee50 commented on src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
> +                }
can you transfer to a function?

2022-03-23 02:23 UTC, karlolee50 requested changes
Review time: 15 minutes
Comment/s: 2

2022-03-23 03:06 UTC, merged