E_CLASSROOM-378 [Improvement] [Student] Removing Retake quiz button
framgia/sph-classroom-els-fe pull request #207
Opened 2022-03-30 10:33 UTC by catampongan

### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-378

### Definition of Done
- [ ] If the user passed the quiz, the "Retake quiz" button should not be displayed

### Commands to Run
N/A

### Notes
#### Main note
- N/A
#### Pages Affected
- http://localhost:3003/
- http://localhost:3003/categories/7/quizzes/7/questions

### Scenarios/ Test Cases
- [ ] If the user passed the quiz, the "Retake quiz" button should not be displayed

### Screenshots
![image](https://user-images.githubusercontent.com/89382692/160812039-ee35d537-becf-4ba7-bfd4-e6cc132ccb9a.png)
![image](https://user-images.githubusercontent.com/89382692/160812081-6e247d16-1dbf-4ec9-b2ca-f11f63d2ce41.png)

2022-03-30 10:42 UTC, karlolee50 commented on src/pages/student/main/Dashboard/components/Recent/index.js
> +                  )}
can you change this to a normal 'if' statement so that there is no else statement where it is just blank?

2022-03-30 10:42 UTC, karlolee50 commented on src/pages/student/quizzes/QuizResult/index.js
> +                  )}
same with my previous comment

2022-03-30 10:42 UTC, karlolee50 requested changes
Review time: 5 minutes
Comment/s: 2

2022-03-31 01:55 UTC, Teraaay commented
### Approved PR #207 

- [x] Able to remove retake button if the user passed the quiz both on dashboard and quiz result page.

### Screenshot/s
Dashboard
> ![image](https://user-images.githubusercontent.com/91049234/160960526-e52cc1bb-a59b-489e-a57c-13bed3ebebe2.png)

Quiz Result
> ![image](https://user-images.githubusercontent.com/91049234/160960560-bc5cc870-3034-4b9f-8e06-24bd67ad4eb3.png)
> ![image](https://user-images.githubusercontent.com/91049234/160960627-d9f43ae1-3853-437a-8047-ee0adc403ce2.png)

----
- Total Test time: 10 mins
- Total Iterations: 0
- Total Comments: 0

2022-03-31 02:46 UTC, karlolee50 approved these changes

2022-03-31 02:47 UTC, merged