E_CLASSROOM-215-FE/BE-Profile-Edit-Function - first commit
framgia/sph-classroom-els-fe pull request #76
Opened 2022-01-24 03:39 UTC by CaneteJoash

### Issue Link

### Definition of Done
- [ ] 
- [ ] 

### Commands to Run

### Notes
#### Main note
- 
#### Pages Affected
- 

### Scenarios/ Test Cases
- [ ] it should `expected behavior` when `condition` 
#### User Interface
- [ ] when `action` should `expected behavior`
#### User Experience 
- [ ] when `action` should `expected behavior`
#### Functionality
- [ ] it should return value when `action`
### Screenshots

2022-01-27 02:39 UTC, catampongan commented
### Working
- [x] Able to change user's name

### Comment
- Edit the validation message

---------
![name-change2](https://user-images.githubusercontent.com/89382692/151281790-ce9ae0f4-7c13-4d01-ab58-f182372be990.gif)
![Screenshot 2022-01-27 103719](https://user-images.githubusercontent.com/89382692/151282054-e2b28045-c5df-496c-8f7b-9a98186bd825.png)

-------

- Total Test Time: 0.5 hr

2022-01-28 03:14 UTC, catampongan commented
### Working
- [x] Able to change user's name
- [x] Able to display validation message

### Comment
- [ ] Fix the UI of the button
- [ ] Account Info page should be dynamic and the inputs should not clickable
- [ ] Since it takes to long to load the edit form, should implement a spinner and make sure the edit form displays as a whole

--------

![Screenshot 2022-01-28 110520](https://user-images.githubusercontent.com/89382692/151480756-99df0bee-22ad-488c-95bb-2cd8010cb9fe.png)

![Screenshot 2022-01-28 110521](https://user-images.githubusercontent.com/89382692/151480818-aa454cfd-8b1d-4209-9b79-6bdde725f04f.png)

![name-change3](https://user-images.githubusercontent.com/89382692/151481026-fcdebca1-1d9c-488d-a2ea-b7657dbb2766.gif)

------
- Total Test Time: 0.75 hr

2022-01-28 07:35 UTC, catampongan commented
## Approved PR #76 
- [x] Able to change user's name
- [x] Able to display validation message
- [x] Fixed the button
- [x] Able to make the account info dynamic and make the inputs unclickable
- [x] Able to add spinner due to the delay

-------
![name-change4](https://user-images.githubusercontent.com/89382692/151505139-d058a42e-0610-4228-b950-983e626c126f.gif)
![Screenshot 2022-01-28 153140](https://user-images.githubusercontent.com/89382692/151505650-16959557-2563-4834-8593-074ad0bc2b3e.png)
![Screenshot 2022-01-28 153346](https://user-images.githubusercontent.com/89382692/151505798-1787b60f-eb9f-4bcb-972c-504270661579.png)

------

- Total Test Time: 1 hr
- Total Iterations: 2
- Total Comments:  3

2022-01-28 08:18 UTC, karlolee50 commented on src/api/Base/index.js
> +    'Content-Type': 'application/json; multipart/form-data',
please remove the multipart/form-data. 
```suggestion
    'Content-Type': 'application/json',
```

2022-01-28 08:22 UTC, karlolee50 commented on src/pages/student/profile/EditProfile/index.js
> +              <Form.Label style={{ marginBottom: '0px', color: '#48535B' }}>
please use a class instead since the code on line 157 also has the same style

2022-01-28 08:22 UTC, karlolee50 commented on src/pages/student/profile/EditProfile/index.js
> +                }}
please check if you can use a class here as well. this has the same style with lines 125 and 157. the difference is only the font-size

2022-01-28 08:23 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +  // };
remove if not used

2022-01-28 08:23 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +    console.log(file);
remove if not used

2022-01-28 08:23 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +    console.log(image[0]);
remove if not used

2022-01-28 08:24 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +  // };
remove if not used

2022-01-28 08:24 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +            <input type='file' name='image'  ref={control} accept='image/png, image/jpeg'  className={style.modalform}  onChange={onChange}/> */}
remove if not used

2022-01-28 08:24 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +                  // value={value}
remove if not used

2022-01-28 08:24 UTC, karlolee50 commented on src/pages/student/profile/ProfileDetail/index.js
> +                  // ref={ref}
remove if not used

2022-01-28 08:26 UTC, karlolee50 commented on src/pages/student/profile/ProfileView/index.js
> +                  fontSize: '16px',
same style with line 65. check if you can use class here as well

2022-01-28 08:28 UTC, karlolee50 requested changes
Review time: 20 mins
Comment/s: 6

2022-01-28 09:31 UTC, karlolee50 approved these changes

2022-01-28 09:34 UTC, merged