E_CLASSROOM-229 [Admin] [UI] Category List Page
framgia/sph-classroom-els-fe pull request #87
Opened 2022-01-31 09:10 UTC by ErickDoroy

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-229
### Definition of Done
- [x] Searchbar is displayed
- [x] (Skip) Filter dropdown is displayed
- [x] Table is displayed with correct columns
- [x] No need for the image to be displayed
- [x] Edit/delete buttons are visible
- [x] Description column not needed 

### Commands to Run

### Notes
#### Main note
- http://localhost:3003/admin/categories
#### Pages Affected
- 

### Scenarios/ Test Cases
- [ ] N/A
#### User Interface
- [ ] N/A
#### User Experience 
- [ ] N/A
#### Functionality
- [ ] N/A
### Screenshots
![admincat](https://user-images.githubusercontent.com/89514595/151766735-906f5c6f-dcff-44e8-873d-afdce57ff36c.PNG)

2022-01-31 10:32 UTC, karlolee50 commented on src/pages/admin/categories/CategoryList/index.js
> +                    </tr>
instead of displaying one by one, please make a variable containing all dummy data and loop through it. in the loop, display each of the items

2022-01-31 10:34 UTC, karlolee50 commented on src/pages/admin/categories/CategoryList/index.module.css
> +}
add extra line

2022-01-31 10:35 UTC, karlolee50 commented on src/pages/admin/categories/CategoryList/index.module.css
> +.Bodystyle{
please use sass instead of css

2022-01-31 10:36 UTC, karlolee50 requested changes
Review time: 15 minutes
Comment/s: 3

2022-01-31 11:03 UTC, catampongan commented
## Approved PR #87 
- [x] Displays search bar
- [x] Table is displayed with columns arranged correctly same in Figma
- [x]  Edit/Delete icons are displayed

---------
![Screenshot 2022-01-31 190005](https://user-images.githubusercontent.com/89382692/151782523-1f63c928-a8ee-4780-b423-b2079809d259.png)
---------
- Total Test Time: 0.25 hr
- Total Iterations: 0
- Total Comments: 0

2022-02-02 06:54 UTC, karlolee50 approved these changes

2022-02-02 07:08 UTC, merged