E_CLASSROOM-231 Category Add/Edit Form
framgia/sph-classroom-els-fe pull request #90
Opened 2022-02-03 06:38 UTC by catampongan

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-231

### Definition of Done
- [ ] Add form is correctly displayed according to the Figma design
- [ ] Edit form is correctly displayed according to the Figma design
- [ ] Card titles changes if user is adding/editing a category
- [ ] Button text changes if user is adding/editing a category
- [ ] When clicking back button, redirect to list page

### Commands to Run
- N/A

### Notes
#### Main note
-  Login as an admin user
#### Pages Affected
- http://localhost:3003/admin/add-category
- http://localhost:3003/admin/edit-category

### Scenarios/ Test Cases
- [ ] Add form is correctly displayed according to the Figma design
- [ ] Edit form is correctly displayed according to the Figma design
- [ ] Card titles changes if user is adding/editing a category
- [ ] Button text changes if user is adding/editing a category
- [ ] When clicking back button, redirect to list page
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
![add](https://user-images.githubusercontent.com/89382692/152293448-6de31531-6c4e-4392-9f7f-9da8283d1a09.png)
![edit](https://user-images.githubusercontent.com/89382692/152293489-2670dd04-4d4c-45cc-b5c9-66fdf0eb96fe.png)

2022-02-03 08:37 UTC, karlolee50 commented on src/pages/admin/categories/AddCategory/index.js
>  export default AddCategory;
can we make just one AddEditCategory file and pass props to indicate whether we will be adding or editing a category? we can name the file 'CategoryUpsertForm'

2022-02-03 08:38 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 1

2022-02-03 08:48 UTC, Teraaay commented
### Working
- [x] Able to display edit and add category form
- [x] Able to follow the placement of the Icons, Inputs, buttons the same as Figma
- [x] Able to redirect to the Categories list when clicking the back button 

### Comment
- [ ] The back button on both forms are too big.
- [ ] The add and edit form is not displayed in the center [left and right sides of the form has different sizes]. Please display it in the center
- [ ] The input fields, buttons, and texts inside the form are too close to the side. Please apply padding.

Please refer to the screenshot below.
     
### Screenshot
![image](https://user-images.githubusercontent.com/91049234/152309911-19e5f03a-50c0-45d3-837f-2cf7a61b23d4.png)

------
- Total Test Time: 0.25 hr

2022-02-04 09:39 UTC, karlolee50 approved these changes

2022-02-04 10:07 UTC, Teraaay commented
### Approved PR #90
- [x] Able to display edit and add category form
- [x] Able to follow the placement of the Icons, Inputs, buttons the same as Figma
- [x] Able to redirect to the Categories list when clicking the back button
- [x] Able to fix the form's position, back button size, and input alignments.
- [x] Able to fix the admin sidebar,

### Screenshot/s
![image](https://user-images.githubusercontent.com/91049234/152510355-57d6b16e-d291-4726-b0f7-7b62a45e8a67.png)

![image](https://user-images.githubusercontent.com/91049234/152510390-ad344c94-257c-4b5e-9c10-3f6bcdeead08.png)

----
- Total Test time: 0.5 hr
- Total Iterations: 1
- Total Comments: 2

2022-02-04 10:13 UTC, merged