E_CLASSROOM-234 [Admin] [FE/BE] Dynamic Data for Displaying Categories List
framgia/sph-classroom-els-fe pull request #91
Opened 2022-02-03 08:21 UTC by Teraaay

### Issue Link

https://framgiaph.backlog.com/view/E_CLASSROOM-234

### Definition of Done
- [x] Categories are dynamically displayed: Title and Description
- [x] Pagination is working

### Commands to Run
N/A
### Notes
#### Main note
- N/A
#### Pages Affected

- http://localhost:3003/admin/categories

### Scenarios/ Test Cases
- [ ] it should `display the dynamic id, name, and description of the parent categories` when `viewing the categories list [Admin Side]` 
- [ ] it should `display the second list of parent categories` when `changing the page number of the pagination`

### Screenshots
![image](https://user-images.githubusercontent.com/91049234/152305785-2fc91a27-150c-4737-acce-cb108f5931f5.png)

2022-02-03 08:49 UTC, karlolee50 commented on src/pages/admin/categories/CategoryList/index.js
> +            ></Pagination>
```suggestion
          <div id={style.paginateStyle}>
            <Pagination
              page={page}
              perPage={perPage}
              totalItems={totalItems}
              pageCount={lastPage}
              onPageChange={onPageChange}
            />
```

2022-02-03 08:49 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 1

2022-02-04 07:10 UTC, catampongan commented
## Approved PR #91 
- [x] Title and description is displayed dynamically
- [x] Pagination is working

------
![category-list](https://user-images.githubusercontent.com/89382692/152486856-80b237e0-f364-446a-9e50-2adc1bab0f05.gif)
![category-list-1](https://user-images.githubusercontent.com/89382692/152486872-63586ccc-d94c-49eb-93e2-e87c5240d741.png)
------
- Total Test Time: 0.25 hr
- Total Iterations: 0
- Total Comments: 0

2022-02-04 09:36 UTC, karlolee50 approved these changes

2022-02-04 09:37 UTC, merged