E_CLASSROOM-236 [Student][Learnings][FE/BE] Display all quizzes
framgia/sph-classroom-els-fe pull request #94
Opened 2022-02-08 05:14 UTC by ErickDoroy

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-236
### Definition of Done
- [x] All quizzes are displayed
- [x] Pagination is working, maximum of 12 per page
- [x] Display the category and subcategory where the quiz is associated
- [x] No need for filter and header information
- [x] When clicking the item, redirect to results page

### Commands to Run

### Related PR:
- https://github.com/framgia/sph-classroom-els-be/pull/47

### Notes
#### Main note
- http://localhost:3003/learnings
#### Pages Affected
- N/A

### Scenarios/ Test Cases
- [ ] All quizzes are displayed
- [ ] Pagination is working, maximum of 12 per page
- [ ] Display the category and subcategory where the quiz is associated
- [ ] When clicking the item, redirect to results page
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
![learnquiz1](https://user-images.githubusercontent.com/89514595/152918584-519f7750-8698-4f4f-9276-38c8757bd950.PNG)

2022-02-08 08:32 UTC, catampongan commented
## Comment
- [ ] Scrollbar should only be available when it is scrollable
- [ ] Fix the position of scrollbar
- [ ] Other categories that I have learned does not display on the learning page
- [ ] Center the label
- Search
- Categories
- Description

-----
`Scrollbar`

![Screenshot 2022-02-08 161804](https://user-images.githubusercontent.com/89382692/152947256-87020e7f-f0b6-4450-9f2b-8f7c19e970d9.png)

`Label`

![Screenshot 2022-02-08 161804](https://user-images.githubusercontent.com/89382692/152947541-a7340e5b-c859-4d17-accc-8887c5b1eeb3.png)

`Categories Learned`

![Screenshot 2022-02-08 161815](https://user-images.githubusercontent.com/89382692/152948287-75dc0fb4-fbee-46f6-bd46-0c8414b0e0ee.png)

----------
- Total Test Time: 1.25 hr

2022-02-08 11:18 UTC, catampongan commented
## Working
- [x] Displays the category and subcategory where the quiz is associated
- [x] Scrollbar should only be available when it is scrollable and fix the position of scrollbar
- [x] Other categories that I have learned does not display on the learning page
## Comment
- [ ] Pagination is not working
---------
![learnings](https://user-images.githubusercontent.com/89382692/152976619-8aad3d3e-f912-434e-9698-4fe3638f1de6.gif)
--------
- Total Test Time: 1.5 hr

2022-02-09 09:04 UTC, catampongan commented
## Approved PR #94 
- [x] Displays the category and subcategory where the quiz is associated
- [x] Scrollbar should only be available when it is scrollable and fix the position of scrollbar
- [x] Other categories that I have learned does not display on the learning page
- [x] Pagination is not working
---------
![Screenshot 2022-02-09 170223](https://user-images.githubusercontent.com/89382692/153161547-f2517d9b-152d-4bc0-ba3e-1196b1d48325.png)

![Screenshot 2022-02-09 170252](https://user-images.githubusercontent.com/89382692/153161562-381cd92c-8f4c-4570-a5fc-b96289e63a3f.png)
--------
- Total Test Time: 1.75 hr
- Total Iterations: 2
- Total Comments: 4

2022-02-09 09:10 UTC, karlolee50 commented on src/pages/student/categories/CategoryList/index.js
> +      console.log(data.data);
remove if not needed

2022-02-09 09:11 UTC, karlolee50 commented on src/api/Learning/index.js
> +export default LearningApi;
add extra line
```suggestion
export default LearningApi;

```

2022-02-09 09:11 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 2

2022-02-09 09:28 UTC, karlolee50 approved these changes

2022-02-09 09:47 UTC, merged